#!/bin/bash

echo "🚀 LogRocket Setup Script"
echo "========================="
echo ""

# Install dependencies
echo "📦 Installing LogRocket packages..."
npm install logrocket logrocket-react

echo ""
echo "✅ Installation complete!"
echo ""
echo "📝 Next steps:"
echo ""
echo "1. Create a LogRocket account at https://logrocket.com"
echo "2. Create a new app/project"
echo "3. Copy your App ID (format: abc123/campaign-quiz)"
echo ""
echo "4. Add to .env.local:"
echo "   NEXT_PUBLIC_LOGROCKET_APP_ID=\"your-app-id/campaign-quiz\""
echo ""
echo "5. Add to Vercel environment variables:"
echo "   Go to: https://vercel.com/jessica-rosenbergs-projects/campaign-quiz/settings/environment-variables"
echo "   Add: NEXT_PUBLIC_LOGROCKET_APP_ID"
echo ""
echo "6. Update app/layout.tsx to include:"
echo "   import { LogRocketProvider } from '@/components/LogRocketProvider';"
echo "   import { ErrorBoundary } from '@/components/ErrorBoundary';"
echo ""
echo "   Then wrap your app:"
echo "   <LogRocketProvider />"
echo "   <ErrorBoundary>"
echo "     {children}"
echo "   </ErrorBoundary>"
echo ""
echo "7. Deploy to Vercel:"
echo "   vercel --prod"
echo ""
echo "8. Test by triggering an error in your app"
echo ""
echo "📚 Full setup guide: docs/LOGROCKET_SETUP.md"
echo ""
